### ISSUE TITLE
Missing Austria language

### ISSUE THREAD

**Issue by kpengineer** [rinvex/language#15]
Hello Support Team
on languages.json file, i don't see language and information for the Austria country, can you please do some checks?
Thank you

**Comment by kpengineer** [comment]
I've tried to add some custom line and it works
`"at": {
    "name": "Austria",
    "native": "Österreich",
    "iso_639_1": "at",
    "iso_639_2": "bar",
    "iso_639_3": "bar",
    "script": {
      "name": "Latin",
      "iso_15924": "Latn",
      "iso_numeric": "215",
      "direction": "ltr"
    },
    "family": {
      "name": "Indo-European",
      "iso_639_5": "ine",
      "hierarchy": "ine"
    },
    "cultures": {
      "de-AT": {
        "name": "German (Austria)",
        "native": "Deutsch (Österreich)"
      }
    },
    "scope": "individual",
    "type": "living"
  },`

**Comment by Omranic** [comment]
Hello @drupalex10 

Thank you for your suggestion, however this package is for languages, not countries. For countries please check https://github.com/rinvex/countries

In regard to your concern, please check the **German** language, which has the following cultures:
```

        "cultures": {
            "de-AT": {
                "name": "German (Austria)",
                "native": "Deutsch (Österreich)"
            },
            "de-BE": {
                "name": "German (Belgium)",
                "native": "Deutsch (Belgien)"
            },
            "de-CH": {
                "name": "German (Switzerland)",
                "native": "Deutsch (Schweiz)"
            },
            "de-DE": {
                "name": "German (Germany)",
                "native": "Deutsch (Deutschland)"
            },
            "de-LI": {
                "name": "German (Liechtenstein)",
                "native": "Deutsch (Liechtenstein)"
            },
            "de-LU": {
                "name": "German (Luxembourg)",
                "native": "Deutsch (Luxemburg)"
            }
        },
```

If that's not what you're looking for, would you kindly clarify it in more details so we can adjust or fix what need to be fixed? Also feel free to submit any PRs to this package :)
