### ISSUE TITLE
Missing ISO 639-2/B code

### ISSUE THREAD

**Issue by ihsudg** [rinvex/language#19]
We have only getIso6392() method which returns ISO 639-2/T code. But ISO 639-2/B is not defined and the code is different. See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

For example 

ISO language name | 639-1 | 639-2/T | 639-2/B | 639-3
-- | -- | -- | -- | --
French | fr | fra | fre | fra

**Comment by Omranic** [comment]
@ihsudg thank you for your suggestion, this is good improvement I'd love to see.

I'll be happy to consider any PRs adding this feature and updating the language files with the relative info. All PRs are welcome 🙂
