### ISSUE TITLE
Languages discrepency between this package and rinvex/countries

### ISSUE THREAD

**Issue by tmannherz** [rinvex/language#24]
We use both this repo and `rinvex/countries` in different capacities and have noticed that there are 41 languages in `rinvex/countries` that are not present in this repo.

```
    [arc] => Aramaic
    [bar] => Austro-Bavarian German
    [bjz] => Belizean Creole
    [ber] => Berber
    [cal] => Carolinian
    [bwg] => Chibarwe
    [zdj] => Comorian
    [rar] => Cook Islands Māori
    [prs] => Dari
    [hif] => Fiji Hindi
    [fil] => Filipino
    [gil] => Gilbertese
    [nfr] => Guernésiais
    [mey] => Hassaniya
    [jam] => Jamaican Patois
    [nrf] => Jèrriais
    [kck] => Kalanga
    [hgm] => Khoekhoe
    [khi] => Khoisan
    [kwn] => Kwangali
    [loz] => Lozi
    [cmn] => Mandarin
    [mfe] => Mauritian Creole
    [ndc] => Ndau
    [nzs] => New Zealand Sign Language
    [niu] => Niuean
    [pih] => Norfuk
    [nso] => Northern Sotho
    [pau] => Palauan
    [pap] => Papiamento
    [smi] => Sami
    [crs] => Seychellois Creole
    [ckb] => Sorani
    [gsw] => Swiss German
    [tet] => Tetum
    [tpi] => Tok Pisin
    [tkl] => Tokelauan
    [toi] => Tonga
    [lua] => Tshiluba
    [tvl] => Tuvaluan
    [zib] => Zimbabwean Sign Language
```

I suppose you could argue about some above but Mandarin is spoken by almost a billion people and should probably be included in this repo's list.

Thank you for supporting both repos!

**Comment by Omranic** [comment]
Thank you for the good suggestion, I'll be happy to consider any PRs to improve this functionality.

**Comment by tmannherz** [comment]
Is there a data source that you use to pull the existing language data?

**Comment by Omranic** [comment]
Actually it was gathered from different sources, which was cumbersome at the time 🫤

I'm not aware if there's some standard sources we can rely on at the moment.
